version: '3.1'
services:
  stats-server:
    build: ewm-stats/stats-server/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=pguser
      - SPRING_DATASOURCE_PASSWORD=pgpassword

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword

  ewm-service:
    build: ewm-main
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EWM_STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=pguser
      - SPRING_DATASOURCE_PASSWORD=pgpassword

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword